language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install pytest codecov pytest-cov

script:
  - pytest --cov-report term-missing --cov="archive_workdir.archive_workdir" tests/

after_success:
  - codecov